periodo_simulacion: 10 # Inidad segundos. Por defecto 20 segundos 
tiempo_simulacion: 20 # Unidad segundos. Por defecto 60 segundos
num_registros: 5 # Cantidad de registros a generar por periodo de simulaci√≥n. Por defecto 100
min_log_file: 1
max_log_file: 1000
min_lineas: 5
